/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BlobReference = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LinkData = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'logoReference' : BlobReference,
  'displayText' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const EntitlementData = IDL.Record({
  'id' : IDL.Nat,
  'files' : IDL.Vec(BlobReference),
  'logoReference' : IDL.Opt(BlobReference),
  'documentReference' : IDL.Opt(IDL.Text),
  'properties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'issuer' : IDL.Text,
  'resourceName' : IDL.Text,
});
export const ProfileInput = IDL.Record({
  'name' : IDL.Text,
  'links' : IDL.Vec(LinkData),
  'entitlements' : IDL.Vec(EntitlementData),
  'additionalFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const Profile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const Profile__1 = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'links' : IDL.Vec(LinkData),
  'entitlements' : IDL.Vec(EntitlementData),
  'additionalFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, BlobReference],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntitlement' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(BlobReference),
        IDL.Vec(BlobReference),
      ],
      [IDL.Nat],
      [],
    ),
  'createProfile' : IDL.Func([ProfileInput], [], []),
  'deleteProfile' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntitlements' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EntitlementData)],
      ['query'],
    ),
  'getLinks' : IDL.Func([IDL.Principal], [IDL.Vec(LinkData)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile__1], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeEntitlement' : IDL.Func([IDL.Nat], [], []),
  'removeLink' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'updateProfile' : IDL.Func([ProfileInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BlobReference = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LinkData = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'logoReference' : BlobReference,
    'displayText' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const EntitlementData = IDL.Record({
    'id' : IDL.Nat,
    'files' : IDL.Vec(BlobReference),
    'logoReference' : IDL.Opt(BlobReference),
    'documentReference' : IDL.Opt(IDL.Text),
    'properties' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'issuer' : IDL.Text,
    'resourceName' : IDL.Text,
  });
  const ProfileInput = IDL.Record({
    'name' : IDL.Text,
    'links' : IDL.Vec(LinkData),
    'entitlements' : IDL.Vec(EntitlementData),
    'additionalFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const Profile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const Profile__1 = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'links' : IDL.Vec(LinkData),
    'entitlements' : IDL.Vec(EntitlementData),
    'additionalFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, BlobReference],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntitlement' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(BlobReference),
          IDL.Vec(BlobReference),
        ],
        [IDL.Nat],
        [],
      ),
    'createProfile' : IDL.Func([ProfileInput], [], []),
    'deleteProfile' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntitlements' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EntitlementData)],
        ['query'],
      ),
    'getLinks' : IDL.Func([IDL.Principal], [IDL.Vec(LinkData)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile__1], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeEntitlement' : IDL.Func([IDL.Nat], [], []),
    'removeLink' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'updateProfile' : IDL.Func([ProfileInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };