import type {
  CustomField,
  DropdownOption,
  LabelConfig,
  Session,
  User,
  VoterRecord,
} from "./types";

const KEYS = {
  users: "vmas_users",
  sessions: "vmas_sessions",
  voters: "vmas_voters",
  dropdownOptions: "vmas_dropdown_options",
  customFields: "vmas_custom_fields",
  labelConfig: "vmas_label_config",
} as const;

function getItem<T>(key: string): T[] {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return [];
    return JSON.parse(raw) as T[];
  } catch {
    return [];
  }
}

function setItem<T>(key: string, data: T[]): void {
  localStorage.setItem(key, JSON.stringify(data));
}

function getObject<T>(key: string, defaultVal: T): T {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return defaultVal;
    return JSON.parse(raw) as T;
  } catch {
    return defaultVal;
  }
}

function setObject<T>(key: string, data: T): void {
  localStorage.setItem(key, JSON.stringify(data));
}

// ---- Users ----
export function getUsers(): User[] {
  return getItem<User>(KEYS.users);
}

export function setUsers(users: User[]): void {
  setItem(KEYS.users, users);
}

// ---- Sessions ----
export function getSessions(): Session[] {
  return getItem<Session>(KEYS.sessions);
}

export function setSessions(sessions: Session[]): void {
  setItem(KEYS.sessions, sessions);
}

// ---- Voters ----
export function getVoters(): VoterRecord[] {
  return getItem<VoterRecord>(KEYS.voters);
}

export function setVoters(voters: VoterRecord[]): void {
  setItem(KEYS.voters, voters);
}

// ---- Dropdown Options ----
export function getDropdownOptions(): DropdownOption[] {
  return getItem<DropdownOption>(KEYS.dropdownOptions);
}

export function setDropdownOptions(options: DropdownOption[]): void {
  setItem(KEYS.dropdownOptions, options);
}

// ---- Custom Fields ----
export function getCustomFields(): CustomField[] {
  return getItem<CustomField>(KEYS.customFields);
}

export function setCustomFields(fields: CustomField[]): void {
  setItem(KEYS.customFields, fields);
}

// ---- Label Config ----
export function getLabelConfig(): LabelConfig {
  return getObject<LabelConfig>(KEYS.labelConfig, {
    selectedFields: ["fullName", "voterId", "mobile", "ward", "boothNumber"],
  });
}

export function setLabelConfig(config: LabelConfig): void {
  setObject(KEYS.labelConfig, config);
}

// ---- Seed default data ----
export function seedDefaultData(): void {
  const users = getUsers();
  if (users.length === 0) {
    setUsers([
      {
        userId: "user_1",
        username: "admin",
        passwordHash: "admin123",
        role: "superAdmin",
        mobile: "9999999999",
        createdAt: Date.now(),
      },
      {
        userId: "user_2",
        username: "dataentry",
        passwordHash: "data123",
        role: "dataEntry",
        createdAt: Date.now(),
      },
      {
        userId: "user_3",
        username: "viewer",
        passwordHash: "view123",
        role: "viewer",
        createdAt: Date.now(),
      },
    ]);
  }

  const options = getDropdownOptions();
  if (options.length === 0) {
    const defaultOptions: DropdownOption[] = [
      // Category Labels
      {
        id: "cat_1",
        label: "Supporter",
        category: "categoryLabel",
        sortOrder: 1,
      },
      {
        id: "cat_2",
        label: "Neutral",
        category: "categoryLabel",
        sortOrder: 2,
      },
      {
        id: "cat_3",
        label: "Opponent",
        category: "categoryLabel",
        sortOrder: 3,
      },
      // Gender
      { id: "gen_1", label: "Male", category: "gender", sortOrder: 1 },
      { id: "gen_2", label: "Female", category: "gender", sortOrder: 2 },
      { id: "gen_3", label: "Other", category: "gender", sortOrder: 3 },
      // Education
      { id: "edu_1", label: "Primary", category: "education", sortOrder: 1 },
      { id: "edu_2", label: "Secondary", category: "education", sortOrder: 2 },
      {
        id: "edu_3",
        label: "Higher Secondary",
        category: "education",
        sortOrder: 3,
      },
      { id: "edu_4", label: "Graduate", category: "education", sortOrder: 4 },
      {
        id: "edu_5",
        label: "Post Graduate",
        category: "education",
        sortOrder: 5,
      },
      { id: "edu_6", label: "Doctorate", category: "education", sortOrder: 6 },
      // Religion
      { id: "rel_1", label: "Hindu", category: "religion", sortOrder: 1 },
      { id: "rel_2", label: "Muslim", category: "religion", sortOrder: 2 },
      { id: "rel_3", label: "Christian", category: "religion", sortOrder: 3 },
      { id: "rel_4", label: "Sikh", category: "religion", sortOrder: 4 },
      { id: "rel_5", label: "Buddhist", category: "religion", sortOrder: 5 },
      { id: "rel_6", label: "Jain", category: "religion", sortOrder: 6 },
      { id: "rel_7", label: "Other", category: "religion", sortOrder: 7 },
      // Marital Status
      { id: "mar_1", label: "Single", category: "maritalStatus", sortOrder: 1 },
      {
        id: "mar_2",
        label: "Married",
        category: "maritalStatus",
        sortOrder: 2,
      },
      {
        id: "mar_3",
        label: "Widowed",
        category: "maritalStatus",
        sortOrder: 3,
      },
      {
        id: "mar_4",
        label: "Divorced",
        category: "maritalStatus",
        sortOrder: 4,
      },
      // Profession
      { id: "pro_1", label: "Farmer", category: "profession", sortOrder: 1 },
      { id: "pro_2", label: "Business", category: "profession", sortOrder: 2 },
      {
        id: "pro_3",
        label: "Government Employee",
        category: "profession",
        sortOrder: 3,
      },
      {
        id: "pro_4",
        label: "Private Employee",
        category: "profession",
        sortOrder: 4,
      },
      { id: "pro_5", label: "Student", category: "profession", sortOrder: 5 },
      { id: "pro_6", label: "Homemaker", category: "profession", sortOrder: 6 },
      { id: "pro_7", label: "Retired", category: "profession", sortOrder: 7 },
      // Professional Category
      {
        id: "prc_1",
        label: "Agriculture",
        category: "professionalCategory",
        sortOrder: 1,
      },
      {
        id: "prc_2",
        label: "Commerce",
        category: "professionalCategory",
        sortOrder: 2,
      },
      {
        id: "prc_3",
        label: "Service",
        category: "professionalCategory",
        sortOrder: 3,
      },
      {
        id: "prc_4",
        label: "Self-Employed",
        category: "professionalCategory",
        sortOrder: 4,
      },
      // Booth
      { id: "bth_1", label: "Booth 1", category: "booth", sortOrder: 1 },
      { id: "bth_2", label: "Booth 2", category: "booth", sortOrder: 2 },
      { id: "bth_3", label: "Booth 3", category: "booth", sortOrder: 3 },
      // Ward
      { id: "wrd_1", label: "Ward A", category: "ward", sortOrder: 1 },
      { id: "wrd_2", label: "Ward B", category: "ward", sortOrder: 2 },
      { id: "wrd_3", label: "Ward C", category: "ward", sortOrder: 3 },
      // Constituency
      {
        id: "con_1",
        label: "North Constituency",
        category: "constituency",
        sortOrder: 1,
      },
      {
        id: "con_2",
        label: "South Constituency",
        category: "constituency",
        sortOrder: 2,
      },
      {
        id: "con_3",
        label: "East Constituency",
        category: "constituency",
        sortOrder: 3,
      },
      // Taluka
      { id: "tal_1", label: "Taluka 1", category: "taluka", sortOrder: 1 },
      { id: "tal_2", label: "Taluka 2", category: "taluka", sortOrder: 2 },
      // District
      { id: "dis_1", label: "District A", category: "district", sortOrder: 1 },
      { id: "dis_2", label: "District B", category: "district", sortOrder: 2 },
      // Caste
      { id: "cst_1", label: "General", category: "caste", sortOrder: 1 },
      { id: "cst_2", label: "OBC", category: "caste", sortOrder: 2 },
      { id: "cst_3", label: "SC", category: "caste", sortOrder: 3 },
      { id: "cst_4", label: "ST", category: "caste", sortOrder: 4 },
    ];
    setDropdownOptions(defaultOptions);
  }

  // Seed mock voter data
  if (getVoters().length === 0) {
    const now = Date.now();
    const mockVoters: VoterRecord[] = [
      {
        id: "v001",
        voterId: "MH/01/001",
        fullName: "Ramesh Kumar Sharma",
        fatherHusbandName: "Suresh Sharma",
        gender: "Male",
        dateOfBirth: "1972-03-15",
        mobile: "9823456701",
        address: "12, Shivaji Nagar",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward A",
        constituency: "North Constituency",
        education: "Graduate",
        profession: "Government Employee",
        caste: "General",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 4,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v002",
        voterId: "MH/01/002",
        fullName: "Sunita Devi Patel",
        fatherHusbandName: "Mahesh Patel",
        gender: "Female",
        dateOfBirth: "1985-07-22",
        mobile: "9812345602",
        address: "45, Gandhi Road",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward A",
        constituency: "North Constituency",
        education: "Post Graduate",
        profession: "Homemaker",
        caste: "OBC",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v003",
        voterId: "MH/01/003",
        fullName: "Mohammed Iqbal Khan",
        fatherHusbandName: "Abdul Khan",
        gender: "Male",
        dateOfBirth: "1968-11-08",
        mobile: "9834567803",
        address: "78, Azad Colony",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward B",
        constituency: "North Constituency",
        education: "Secondary",
        profession: "Business",
        caste: "OBC",
        religion: "Muslim",
        categoryLabel: "Neutral",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v004",
        voterId: "MH/01/004",
        fullName: "Gurpreet Singh Bhatia",
        fatherHusbandName: "Harbhajan Singh",
        gender: "Male",
        dateOfBirth: "1979-05-30",
        mobile: "9867890104",
        address: "23, Guru Nanak Street",
        taluka: "Taluka 2",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward B",
        constituency: "North Constituency",
        education: "Graduate",
        profession: "Business",
        caste: "General",
        religion: "Sikh",
        categoryLabel: "Supporter",
        influenceLevel: 5,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v005",
        voterId: "MH/01/005",
        fullName: "Anita Ramesh Desai",
        fatherHusbandName: "Ramesh Desai",
        gender: "Female",
        dateOfBirth: "1990-01-14",
        mobile: "9845678905",
        address: "56, Nehru Nagar",
        taluka: "Taluka 2",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward C",
        constituency: "North Constituency",
        education: "Graduate",
        profession: "Government Employee",
        caste: "SC",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v006",
        voterId: "MH/01/006",
        fullName: "Vijay Baburao Patil",
        fatherHusbandName: "Baburao Patil",
        gender: "Male",
        dateOfBirth: "1963-09-25",
        mobile: "9878901206",
        address: "34, Ambedkar Road",
        taluka: "Taluka 2",
        district: "District A",
        boothNumber: "Booth 2",
        ward: "Ward A",
        constituency: "South Constituency",
        education: "Primary",
        profession: "Farmer",
        caste: "SC",
        religion: "Hindu",
        categoryLabel: "Neutral",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v007",
        voterId: "MH/01/007",
        fullName: "Fatima Begum Shaikh",
        fatherHusbandName: "Salim Shaikh",
        gender: "Female",
        dateOfBirth: "1982-04-18",
        mobile: "9856789307",
        address: "89, Masjid Lane",
        taluka: "Taluka 1",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward A",
        constituency: "South Constituency",
        education: "Secondary",
        profession: "Homemaker",
        caste: "OBC",
        religion: "Muslim",
        categoryLabel: "Supporter",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v008",
        voterId: "MH/01/008",
        fullName: "Suresh Govind Jadhav",
        fatherHusbandName: "Govind Jadhav",
        gender: "Male",
        dateOfBirth: "1975-12-03",
        mobile: "9889012408",
        address: "67, Tilak Chowk",
        taluka: "Taluka 1",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward B",
        constituency: "South Constituency",
        education: "Higher Secondary",
        profession: "Farmer",
        caste: "OBC",
        religion: "Hindu",
        categoryLabel: "Opponent",
        influenceLevel: 1,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v009",
        voterId: "MH/01/009",
        fullName: "Kavita Anil Kulkarni",
        fatherHusbandName: "Anil Kulkarni",
        gender: "Female",
        dateOfBirth: "1994-06-28",
        mobile: "9823456709",
        address: "12, Saraswati Colony",
        taluka: "Taluka 2",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward B",
        constituency: "South Constituency",
        education: "Post Graduate",
        profession: "Government Employee",
        caste: "General",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 4,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v010",
        voterId: "MH/01/010",
        fullName: "Prakash Sadanand More",
        fatherHusbandName: "Sadanand More",
        gender: "Male",
        dateOfBirth: "1960-02-12",
        mobile: "9812345610",
        address: "45, Parbhani Road",
        taluka: "Taluka 2",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward C",
        constituency: "South Constituency",
        education: "Primary",
        profession: "Farmer",
        caste: "ST",
        religion: "Hindu",
        categoryLabel: "Neutral",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v011",
        voterId: "MH/02/001",
        fullName: "Arjun Prabhakaran Nair",
        fatherHusbandName: "Prabhakaran Nair",
        gender: "Male",
        dateOfBirth: "1987-08-16",
        mobile: "9834567811",
        address: "78, Model Colony",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 3",
        ward: "Ward A",
        constituency: "East Constituency",
        education: "Graduate",
        profession: "Private Employee",
        caste: "General",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v012",
        voterId: "MH/02/002",
        fullName: "Rashida Yusuf Mirza",
        fatherHusbandName: "Yusuf Mirza",
        gender: "Female",
        dateOfBirth: "1978-10-05",
        mobile: "9867890112",
        address: "23, Urdu School Lane",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 3",
        ward: "Ward A",
        constituency: "East Constituency",
        education: "Graduate",
        profession: "Homemaker",
        caste: "OBC",
        religion: "Muslim",
        categoryLabel: "Neutral",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v013",
        voterId: "MH/02/003",
        fullName: "Santosh Narayan Bhosle",
        fatherHusbandName: "Narayan Bhosle",
        gender: "Male",
        dateOfBirth: "1971-07-20",
        mobile: "9845678913",
        address: "56, Shivneri Park",
        taluka: "Taluka 2",
        district: "District A",
        boothNumber: "Booth 3",
        ward: "Ward B",
        constituency: "East Constituency",
        education: "Secondary",
        profession: "Farmer",
        caste: "OBC",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 4,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v014",
        voterId: "MH/02/004",
        fullName: "Harpreet Kaur Dhaliwal",
        fatherHusbandName: "Baljit Dhaliwal",
        gender: "Female",
        dateOfBirth: "1996-03-11",
        mobile: "9878901214",
        address: "34, Defence Colony",
        taluka: "Taluka 1",
        district: "District B",
        boothNumber: "Booth 3",
        ward: "Ward B",
        constituency: "East Constituency",
        education: "Graduate",
        profession: "Student",
        caste: "General",
        religion: "Sikh",
        categoryLabel: "Supporter",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v015",
        voterId: "MH/02/005",
        fullName: "Dinesh Harishchandra Wagh",
        fatherHusbandName: "Harishchandra Wagh",
        gender: "Male",
        dateOfBirth: "1966-01-09",
        mobile: "9856789315",
        address: "89, Tilak Path",
        taluka: "Taluka 2",
        district: "District B",
        boothNumber: "Booth 3",
        ward: "Ward C",
        constituency: "East Constituency",
        education: "Higher Secondary",
        profession: "Business",
        caste: "SC",
        religion: "Hindu",
        categoryLabel: "Opponent",
        influenceLevel: 1,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v016",
        voterId: "MH/02/006",
        fullName: "Meena Rajendra Shinde",
        fatherHusbandName: "Rajendra Shinde",
        gender: "Female",
        dateOfBirth: "1983-12-27",
        mobile: "9889012416",
        address: "67, Bhagat Singh Marg",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward A",
        constituency: "North Constituency",
        education: "Primary",
        profession: "Homemaker",
        caste: "ST",
        religion: "Hindu",
        categoryLabel: "Neutral",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v017",
        voterId: "MH/02/007",
        fullName: "Ajay Vinod Kale",
        fatherHusbandName: "Vinod Kale",
        gender: "Male",
        dateOfBirth: "1991-05-04",
        mobile: "9823456717",
        address: "12, New Colony",
        taluka: "Taluka 2",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward B",
        constituency: "North Constituency",
        education: "Post Graduate",
        profession: "Private Employee",
        caste: "General",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 4,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v018",
        voterId: "MH/02/008",
        fullName: "Zubaida Farooq Ansari",
        fatherHusbandName: "Farooq Ansari",
        gender: "Female",
        dateOfBirth: "1974-09-15",
        mobile: "9812345618",
        address: "45, Raza Colony",
        taluka: "Taluka 1",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward A",
        constituency: "South Constituency",
        education: "Secondary",
        profession: "Business",
        caste: "OBC",
        religion: "Muslim",
        categoryLabel: "Neutral",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v019",
        voterId: "MH/02/009",
        fullName: "Mahesh Dattatray Pawar",
        fatherHusbandName: "Dattatray Pawar",
        gender: "Male",
        dateOfBirth: "1969-04-22",
        mobile: "9834567819",
        address: "78, Sainath Nagar",
        taluka: "Taluka 2",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward B",
        constituency: "South Constituency",
        education: "Graduate",
        profession: "Farmer",
        caste: "OBC",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 5,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v020",
        voterId: "MH/02/010",
        fullName: "Pooja Sunil Gaikwad",
        fatherHusbandName: "Sunil Gaikwad",
        gender: "Female",
        dateOfBirth: "1997-11-30",
        mobile: "9867890120",
        address: "23, Ram Nagar",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 3",
        ward: "Ward C",
        constituency: "East Constituency",
        education: "Graduate",
        profession: "Student",
        caste: "SC",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v021",
        voterId: "MH/03/001",
        fullName: "Rajiv Bhaskar Chavan",
        fatherHusbandName: "Bhaskar Chavan",
        gender: "Male",
        dateOfBirth: "1977-06-18",
        mobile: "9845678921",
        address: "56, Laxmi Nagar",
        taluka: "Taluka 2",
        district: "District B",
        boothNumber: "Booth 1",
        ward: "Ward C",
        constituency: "North Constituency",
        education: "Secondary",
        profession: "Business",
        caste: "General",
        religion: "Hindu",
        categoryLabel: "Neutral",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v022",
        voterId: "MH/03/002",
        fullName: "Shaikh Imran Abdul",
        fatherHusbandName: "Abdul Rahim",
        gender: "Male",
        dateOfBirth: "1984-02-07",
        mobile: "9878901222",
        address: "34, Bismillah Lane",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward A",
        constituency: "North Constituency",
        education: "Graduate",
        profession: "Private Employee",
        caste: "OBC",
        religion: "Muslim",
        categoryLabel: "Opponent",
        influenceLevel: 1,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v023",
        voterId: "MH/03/003",
        fullName: "Balwinder Kaur Grewal",
        fatherHusbandName: "Kulwinder Grewal",
        gender: "Female",
        dateOfBirth: "1980-08-14",
        mobile: "9856789323",
        address: "89, Punjab Colony",
        taluka: "Taluka 2",
        district: "District A",
        boothNumber: "Booth 2",
        ward: "Ward B",
        constituency: "South Constituency",
        education: "Higher Secondary",
        profession: "Homemaker",
        caste: "General",
        religion: "Sikh",
        categoryLabel: "Supporter",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v024",
        voterId: "MH/03/004",
        fullName: "Nitin Ashok Mane",
        fatherHusbandName: "Ashok Mane",
        gender: "Male",
        dateOfBirth: "1973-10-01",
        mobile: "9889012424",
        address: "67, Annasaheb Magar Road",
        taluka: "Taluka 1",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward C",
        constituency: "South Constituency",
        education: "Post Graduate",
        profession: "Government Employee",
        caste: "SC",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 4,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v025",
        voterId: "MH/03/005",
        fullName: "Savita Ramkrishna Kamble",
        fatherHusbandName: "Ramkrishna Kamble",
        gender: "Female",
        dateOfBirth: "1988-03-25",
        mobile: "9823456725",
        address: "12, Phule Nagar",
        taluka: "Taluka 2",
        district: "District B",
        boothNumber: "Booth 3",
        ward: "Ward A",
        constituency: "East Constituency",
        education: "Graduate",
        profession: "Homemaker",
        caste: "SC",
        religion: "Hindu",
        categoryLabel: "Neutral",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v026",
        voterId: "MH/03/006",
        fullName: "Prashant Dilip Salve",
        fatherHusbandName: "Dilip Salve",
        gender: "Male",
        dateOfBirth: "1993-07-11",
        mobile: "9812345626",
        address: "45, Green Park",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 3",
        ward: "Ward B",
        constituency: "East Constituency",
        education: "Graduate",
        profession: "Student",
        caste: "ST",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 3,
        isVolunteer: true,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v027",
        voterId: "MH/03/007",
        fullName: "Nooruddin Hassan Siddiqui",
        fatherHusbandName: "Hassan Siddiqui",
        gender: "Male",
        dateOfBirth: "1965-12-19",
        mobile: "9834567827",
        address: "78, Urdu Colony",
        taluka: "Taluka 2",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward C",
        constituency: "North Constituency",
        education: "Secondary",
        profession: "Business",
        caste: "OBC",
        religion: "Muslim",
        categoryLabel: "Neutral",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v028",
        voterId: "MH/03/008",
        fullName: "Rohini Subhash Thorat",
        fatherHusbandName: "Subhash Thorat",
        gender: "Female",
        dateOfBirth: "1970-05-08",
        mobile: "9867890128",
        address: "23, Patel Nagar",
        taluka: "Taluka 1",
        district: "District B",
        boothNumber: "Booth 2",
        ward: "Ward A",
        constituency: "South Constituency",
        education: "Higher Secondary",
        profession: "Farmer",
        caste: "OBC",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 4,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v029",
        voterId: "MH/03/009",
        fullName: "Ganesh Trimbak Shinde",
        fatherHusbandName: "Trimbak Shinde",
        gender: "Male",
        dateOfBirth: "1981-09-03",
        mobile: "9845678929",
        address: "56, Sai Nagar",
        taluka: "Taluka 2",
        district: "District B",
        boothNumber: "Booth 3",
        ward: "Ward B",
        constituency: "East Constituency",
        education: "Primary",
        profession: "Farmer",
        caste: "ST",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 3,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
      {
        id: "v030",
        voterId: "MH/03/010",
        fullName: "Deepa Kiran Sawant",
        fatherHusbandName: "Kiran Sawant",
        gender: "Female",
        dateOfBirth: "1999-01-26",
        mobile: "9878901230",
        address: "34, River View Colony",
        taluka: "Taluka 1",
        district: "District A",
        boothNumber: "Booth 1",
        ward: "Ward B",
        constituency: "North Constituency",
        education: "Post Graduate",
        profession: "Student",
        caste: "General",
        religion: "Hindu",
        categoryLabel: "Supporter",
        influenceLevel: 2,
        isVolunteer: false,
        customValues: [],
        createdAt: now,
        updatedAt: now,
        createdBy: "user_1",
      },
    ];
    setVoters(mockVoters);
  }
}
